// <auto-generated />
using System;
using BE.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BE.Migrations
{
    [DbContext(typeof(StoryReaderDbContext))]
    partial class StoryReaderDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BE.Models.Bookmark", b =>
                {
                    b.Property<int>("BookmarkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookmarkId"));

                    b.Property<int>("ChapterId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastReadAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ScrollPosition")
                        .HasColumnType("int");

                    b.Property<int>("StoryId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("BookmarkId");

                    b.HasIndex("ChapterId");

                    b.HasIndex("StoryId");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "StoryId")
                        .IsUnique();

                    b.ToTable("Bookmarks");
                });

            modelBuilder.Entity("BE.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("CategoryId");

                    b.HasIndex("IsActive");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            IsActive = true,
                            Name = "Hành Động"
                        },
                        new
                        {
                            CategoryId = 2,
                            IsActive = true,
                            Name = "Kinh Dị"
                        },
                        new
                        {
                            CategoryId = 3,
                            IsActive = true,
                            Name = "Lãng Mạn"
                        },
                        new
                        {
                            CategoryId = 4,
                            IsActive = true,
                            Name = "Trinh Thám"
                        });
                });

            modelBuilder.Entity("BE.Models.Chapter", b =>
                {
                    b.Property<int>("ChapterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ChapterId"));

                    b.Property<int>("ChapterNumber")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("ntext");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("PublishedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("StoryId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("ViewCount")
                        .HasColumnType("int");

                    b.HasKey("ChapterId");

                    b.HasIndex("PublishedAt");

                    b.HasIndex("StoryId");

                    b.HasIndex("StoryId", "ChapterNumber")
                        .IsUnique();

                    b.ToTable("Chapters");

                    b.HasData(
                        new
                        {
                            ChapterId = 1,
                            ChapterNumber = 1,
                            Content = "Nội dung chương 1...",
                            IsActive = true,
                            PublishedAt = new DateTime(2026, 3, 28, 8, 20, 57, 701, DateTimeKind.Utc).AddTicks(1331),
                            StoryId = 1,
                            Title = "Hồi kết bắt đầu",
                            ViewCount = 0
                        },
                        new
                        {
                            ChapterId = 2,
                            ChapterNumber = 1,
                            Content = "Nội dung chương 1 kinh dị...",
                            IsActive = true,
                            PublishedAt = new DateTime(2026, 3, 28, 8, 20, 57, 701, DateTimeKind.Utc).AddTicks(1335),
                            StoryId = 2,
                            Title = "Bóng tối",
                            ViewCount = 0
                        });
                });

            modelBuilder.Entity("BE.Models.Comment", b =>
                {
                    b.Property<int>("CommentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CommentId"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("ntext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("StoryId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("CommentId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("StoryId");

                    b.HasIndex("UserId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("BE.Models.Notification", b =>
                {
                    b.Property<int>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NotificationId"));

                    b.Property<int?>("ChapterId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("StoryId")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("NotificationId");

                    b.HasIndex("ChapterId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("StoryId");

                    b.HasIndex("UserId", "IsRead");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("BE.Models.Rating", b =>
                {
                    b.Property<int>("RatingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RatingId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.Property<int>("StoryId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("RatingId");

                    b.HasIndex("StoryId");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "StoryId")
                        .IsUnique();

                    b.ToTable("Ratings");
                });

            modelBuilder.Entity("BE.Models.ReadingMode", b =>
                {
                    b.Property<int>("ModeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ModeId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FontFamily")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("FontSize")
                        .HasColumnType("int");

                    b.Property<decimal>("LineHeight")
                        .HasColumnType("decimal(3,1)");

                    b.Property<string>("NavigationMode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Theme")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("ModeId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("ReadingModes");

                    b.HasData(
                        new
                        {
                            ModeId = -1,
                            CreatedAt = new DateTime(2026, 3, 28, 8, 20, 57, 701, DateTimeKind.Utc).AddTicks(1395),
                            FontFamily = "Georgia",
                            FontSize = 18,
                            LineHeight = 1.8m,
                            NavigationMode = "Scroll",
                            Theme = "Night",
                            UserId = 2
                        });
                });

            modelBuilder.Entity("BE.Models.ReadingProgress", b =>
                {
                    b.Property<int>("ProgressId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProgressId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CurrentChapterId")
                        .HasColumnType("int");

                    b.Property<int?>("CurrentStoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastReadAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("LastReadPosition")
                        .HasColumnType("int");

                    b.Property<int>("TotalChaptersRead")
                        .HasColumnType("int");

                    b.Property<int>("TotalStoriesRead")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("ProgressId");

                    b.HasIndex("CurrentChapterId");

                    b.HasIndex("CurrentStoryId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("ReadingProgresses");

                    b.HasData(
                        new
                        {
                            ProgressId = -1,
                            CreatedAt = new DateTime(2026, 3, 28, 8, 20, 57, 701, DateTimeKind.Utc).AddTicks(1375),
                            CurrentChapterId = 1,
                            CurrentStoryId = 1,
                            LastReadAt = new DateTime(2026, 3, 28, 8, 20, 57, 701, DateTimeKind.Utc).AddTicks(1378),
                            LastReadPosition = 150,
                            TotalChaptersRead = 1,
                            TotalStoriesRead = 1,
                            UserId = 2
                        });
                });

            modelBuilder.Entity("BE.Models.Story", b =>
                {
                    b.Property<int>("StoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StoryId"));

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<decimal>("AverageRating")
                        .HasColumnType("decimal(3,2)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("CoverImage")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("ntext");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("TotalRatings")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ViewCount")
                        .HasColumnType("int");

                    b.HasKey("StoryId");

                    b.HasIndex("AuthorId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ViewCount");

                    b.ToTable("Stories");

                    b.HasData(
                        new
                        {
                            StoryId = 1,
                            AuthorId = 1,
                            AverageRating = 4.5m,
                            CategoryId = 1,
                            CoverImage = "https://picsum.photos/200/300?random=1",
                            CreatedAt = new DateTime(2026, 3, 28, 8, 20, 57, 701, DateTimeKind.Utc).AddTicks(1299),
                            Description = "Truyện hành động hấp dẫn.",
                            IsActive = true,
                            Status = "Ongoing",
                            Title = "Huyền Thoại Sát Thủ",
                            TotalRatings = 1,
                            ViewCount = 1000
                        },
                        new
                        {
                            StoryId = 2,
                            AuthorId = 1,
                            AverageRating = 4.0m,
                            CategoryId = 2,
                            CoverImage = "https://picsum.photos/200/300?random=2",
                            CreatedAt = new DateTime(2026, 3, 28, 8, 20, 57, 701, DateTimeKind.Utc).AddTicks(1312),
                            Description = "Truyện kinh dị kịch tính.",
                            IsActive = true,
                            Status = "Ongoing",
                            Title = "Tiếng Vọng Đêm Khuya",
                            TotalRatings = 1,
                            ViewCount = 500
                        });
                });

            modelBuilder.Entity("BE.Models.StoryFollower", b =>
                {
                    b.Property<int>("FollowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FollowId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("StoryId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("FollowId");

                    b.HasIndex("StoryId");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "StoryId")
                        .IsUnique();

                    b.ToTable("StoryFollowers");

                    b.HasData(
                        new
                        {
                            FollowId = -1,
                            CreatedAt = new DateTime(2026, 3, 28, 8, 20, 57, 701, DateTimeKind.Utc).AddTicks(1358),
                            StoryId = 1,
                            UserId = 2
                        });
                });

            modelBuilder.Entity("BE.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            CreatedAt = new DateTime(2026, 3, 28, 8, 20, 57, 701, DateTimeKind.Utc).AddTicks(1115),
                            Email = "author@test.com",
                            IsActive = true,
                            PasswordHash = "hash123",
                            Username = "author_admin"
                        },
                        new
                        {
                            UserId = 2,
                            CreatedAt = new DateTime(2026, 3, 28, 8, 20, 57, 701, DateTimeKind.Utc).AddTicks(1125),
                            Email = "reader@test.com",
                            IsActive = true,
                            PasswordHash = "hash123",
                            Username = "reader_01"
                        });
                });

            modelBuilder.Entity("BE.Models.Bookmark", b =>
                {
                    b.HasOne("BE.Models.Chapter", "Chapter")
                        .WithMany("Bookmarks")
                        .HasForeignKey("ChapterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BE.Models.Story", "Story")
                        .WithMany("Bookmarks")
                        .HasForeignKey("StoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BE.Models.User", "User")
                        .WithMany("Bookmarks")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chapter");

                    b.Navigation("Story");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BE.Models.Chapter", b =>
                {
                    b.HasOne("BE.Models.Story", "Story")
                        .WithMany("Chapters")
                        .HasForeignKey("StoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Story");
                });

            modelBuilder.Entity("BE.Models.Comment", b =>
                {
                    b.HasOne("BE.Models.Story", "Story")
                        .WithMany("Comments")
                        .HasForeignKey("StoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BE.Models.User", "User")
                        .WithMany("Comments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Story");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BE.Models.Notification", b =>
                {
                    b.HasOne("BE.Models.Chapter", "Chapter")
                        .WithMany("Notifications")
                        .HasForeignKey("ChapterId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BE.Models.Story", "Story")
                        .WithMany("Notifications")
                        .HasForeignKey("StoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BE.Models.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chapter");

                    b.Navigation("Story");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BE.Models.Rating", b =>
                {
                    b.HasOne("BE.Models.Story", "Story")
                        .WithMany("Ratings")
                        .HasForeignKey("StoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BE.Models.User", "User")
                        .WithMany("Ratings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Story");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BE.Models.ReadingMode", b =>
                {
                    b.HasOne("BE.Models.User", "User")
                        .WithOne("ReadingMode")
                        .HasForeignKey("BE.Models.ReadingMode", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BE.Models.ReadingProgress", b =>
                {
                    b.HasOne("BE.Models.Chapter", "CurrentChapter")
                        .WithMany()
                        .HasForeignKey("CurrentChapterId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BE.Models.Story", "CurrentStory")
                        .WithMany()
                        .HasForeignKey("CurrentStoryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BE.Models.User", "User")
                        .WithOne("ReadingProgress")
                        .HasForeignKey("BE.Models.ReadingProgress", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CurrentChapter");

                    b.Navigation("CurrentStory");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BE.Models.Story", b =>
                {
                    b.HasOne("BE.Models.User", "Author")
                        .WithMany("Stories")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BE.Models.Category", "Category")
                        .WithMany("Stories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("BE.Models.StoryFollower", b =>
                {
                    b.HasOne("BE.Models.Story", "Story")
                        .WithMany("Followers")
                        .HasForeignKey("StoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BE.Models.User", "User")
                        .WithMany("StoryFollowers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Story");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BE.Models.Category", b =>
                {
                    b.Navigation("Stories");
                });

            modelBuilder.Entity("BE.Models.Chapter", b =>
                {
                    b.Navigation("Bookmarks");

                    b.Navigation("Notifications");
                });

            modelBuilder.Entity("BE.Models.Story", b =>
                {
                    b.Navigation("Bookmarks");

                    b.Navigation("Chapters");

                    b.Navigation("Comments");

                    b.Navigation("Followers");

                    b.Navigation("Notifications");

                    b.Navigation("Ratings");
                });

            modelBuilder.Entity("BE.Models.User", b =>
                {
                    b.Navigation("Bookmarks");

                    b.Navigation("Comments");

                    b.Navigation("Notifications");

                    b.Navigation("Ratings");

                    b.Navigation("ReadingMode")
                        .IsRequired();

                    b.Navigation("ReadingProgress")
                        .IsRequired();

                    b.Navigation("Stories");

                    b.Navigation("StoryFollowers");
                });
#pragma warning restore 612, 618
        }
    }
}
